#We require sudo access
sudo: required     
#add docker to container created
services: 
  - docker

#instruct travis to create a docker file with our Dockerfile.dev
before_install:
  -  docker build -t nsovomashaba/docker-react -f Dockerfile.dev .               

env: 
  - CI=true
#-- --coverage ensures that the npm run test ends after running once 
script:
  - docker run -e CI=true nsovomashaba/docker-react npm run test -- --coverage

before_deploy:
  - echo $AWS_ACCESS_KEY
  - echo $AWS_SECRET_KEY

deploy:
  provider: elasticbeanstalk
   #aws region where the container is located, DockerReact-env.eba-8xqfk7i4.us-east-2.elasticbeanstalk.com
  region: "us-east-2"
  app: "docker-react"              
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-679308915134"
  bucket_path: "docker-react"
  #only attempt to deploy when we push code to master
  on: 
    branch: master
     #generate API keys on aws - use travic CI to store the key do not store this in the file 
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
 

